version: '3.0'
services:
  main:
    image: react2022/picbu
    container_name: main
#    build:
#      context: app
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
